# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170319_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043d\u0435\u0432\u043d\u0438\u043a\u0430'),
        ),
    ]
