# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170328_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
